### ISSUE TITLE
white screen issue on mac for build based on fork 2272

### ISSUE THREAD

**Issue by suneel-tokuri** [wjywbs/javacef#28]
Hi, We are trying to build javacef for Mac (Yosemite/El capitan) based on fork 2272

we have used _cefclient/osr_widget_mac.h_  in place of _cefclient/cefclient_osr_widget_mac.h_  for cefclient_mac.mm implementation and resolved few compile errors.

We are getting white screen upon launching sample swt browser app. 

Please let us know any possible patch/pointer to missing implementation to resolve the issue.

Thanks in advance,
Suneel

**Comment by wjywbs** [comment]
I spent some time updating to 2526 branch. On mac, it also shows a blank/grey screen, but the web page is loaded and right click works. It can print and save, but no popups yet. On linux, it crashes in x11. I didn't test on windows.

**Comment by suneel-tokuri** [comment]
disable gpu rendering now shows the browser content.

For context menu, we have tried NSApplication implementations from,

https://bitbucket.org/chromiumembedded/java-cef/src/8dce678851ef3b858aceb87c7b1cf07b2e68196d/native/util_mac.mm?at=master&fileviewer=file-view-default
https://github.com/cztomczak/cefpython/blob/v31.2/cefpython/cef3/client_handler/util_mac.mm

Both of these doesn't seems to work. 

First few lines of the stack:

```
[0404/174834:FATAL:scoped_sending_event.mm(14)] Check failed: [app_ conformsToProtocol:@protocol(CrAppControlProtocol)]. 
0   Chromium Embedded Framework         0x000000011c09e83f base::debug::StackTrace::StackTrace() + 47
1   Chromium Embedded Framework         0x000000011c09e893 base::debug::StackTrace::StackTrace() + 35
2   Chromium Embedded Framework         0x000000011c1213d6 logging::LogMessage::~LogMessage() + 70
3   Chromium Embedded Framework         0x000000011c120423 logging::LogMessage::~LogMessage() + 35
4   Chromium Embedded Framework         0x000000011c1349be base::mac::ScopedSendingEvent::ScopedSendingEvent() + 318
5   Chromium Embedded Framework         0x000000011c134a93 base::mac::ScopedSendingEvent::ScopedSendingEvent() + 35
6   Chromium Embedded Framework         0x000000011c04e6e5 CefMenuCreatorRunnerMac::RunContextMenu(CefMenuCreator*) + 549
7   Chromium Embedded Framework         0x000000011be3e44e CefMenuCreator::CreateContextMenu(content::ContextMenuParams const&) + 1438
8   Chromium Embedded Framework         0x000000011bdaa48a CefBrowserHostImpl::HandleContextMenu(content::ContextMenuParams const&) + 154
9   Chromium Embedded Framework         0x000000011bdaa4f4 non-virtual thunk to CefBrowserHostImpl::HandleContextMenu(content::ContextMenuParams const&) + 52
10  Chromium Embedded Framework         0x0000000122e85986 content::WebContentsImpl::ShowContextMenu(content::RenderFrameHost*, content::ContextMenuParams const&) + 246
11  Chromium Embedded Framework         0x0000000122e85a7c non-virtual thunk to content::WebContentsImpl::ShowContextMenu(content::RenderFrameHost*, content::ContextMenuParams const&) + 60

```

**Comment by wjywbs** [comment]
Thanks, I will try to disable gpu. If this works, I could publish my experimental 2526 branch.

**Comment by wjywbs** [comment]
I published my experimental 3.2526 branch: https://github.com/wjywbs/javacef/tree/3.2526. GPU compositing is disabled. Context menu works but popup windows are not supported now.

**Comment by suneel-tokuri** [comment]
Hi, thanks, I'll try checking this new branch.

With gpu compositing disabled we saw painting issues with certain pages on Mac retina display. We have a use case, where we zoom the dom using css and it causes the whole screen turn into boxes that are not getting painted and page is not recovering from that state. Certainly the app has some heavy mark up. 

Previous Macs with normal display doesn't seems to have this problem.

Please let us know any pointers to get the gpu rendering working for Mac retina display.

**Comment by wjywbs** [comment]
Which flag did you use? I used "disable-gpu-compositing" instead of "disable-gpu" in my branch, so it still uses gpu for other things. I haven't find out why gpu compositing does not work. Maybe it's related to whether the NSWindow of SWT allows/supports OpenGL.

**Comment by suneel-tokuri** [comment]
Using "disable-gpu-compositing" doesn't seems to be fixing the issue though this flag is enough to get the rendering working. (we were using "disable-gpu" flag earlier to your response)
