### ISSUE TITLE
Is there any demo application based on javacef?

### ISSUE THREAD

**Issue by jreznot** [wjywbs/javacef#30]
I try to understand how to use javacef in my project, but I cannot find binaries or manual on creating java apps. Is there jar binaries for building my application or just step-by-step guide on simple java application with javacef ?

**Comment by wjywbs** [comment]
You can build javacef3 using this wiki: https://github.com/wjywbs/javacef/blob/wiki/CEF3Instructions.md and [SampleWindow](https://github.com/wjywbs/javacef/blob/master/cef3/java/src/org/embedded/browser/SampleWindow.java) is the simplest example.

**Comment by jreznot** [comment]
Oh, thank you!
Do you plan to provide binaries of JCEF in the future?

**Comment by wjywbs** [comment]
For binary releases, please see #39.
