### ISSUE TITLE
Running SampleBrowserSWT sample app on 2623 fork is resulting in crash on Mac

### ISSUE THREAD

**Issue by giridev** [wjywbs/javacef#33]
Hi,
    Having followed the steps to build javacef as specified in javacef/CEF3Instructions.md for Mac (picking the CEF 2623 build and placing the cefyclient.app in the dir). After the build is successful and run these commands on the terminal 
# Run SampleBrowserSWT
# You can change run.sh to open SampleWindow.

tools/run.sh mac64
tools/run.sh mac64 release

It is resulting in crash. Here is the crash dump 

KH003-MAC1:cef3user$ ./tools/run.sh mac64
Running Debug build.
###### ## APP PATH

/Users/xyz/javacef-3.2623/cef3/cef_runtime/mac64/cefclient.app
JAVAHOME .. /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/
JAVA_BIN .. /bin/java
JAVACEF_PATH .. /Users/xyz/javacef-3.2623/cef3
[0608/175524:FATAL:bundle_locations.mm(62)] Check failed: new_bundle. Failed to load the bundle at Contents/Frameworks/Chromium Embedded Framework.framework
0   Chromium Embedded Framework         0x00000001213c60df _ZN4base5debug10StackTraceC2Ev + 47
1   Chromium Embedded Framework         0x00000001213c6283 _ZN4base5debug10StackTraceC1Ev + 35
2   Chromium Embedded Framework         0x0000000121442060 _ZN7logging10LogMessageD2Ev + 80
3   Chromium Embedded Framework         0x000000012143f993 _ZN7logging10LogMessageD1Ev + 35
4   Chromium Embedded Framework         0x0000000121444456 _ZN4base3macL18AssignOverridePathERKNS_8FilePathEPP8NSBundle + 422
5   Chromium Embedded Framework         0x00000001214444fa _ZN4base3mac30SetOverrideFrameworkBundlePathERKNS_8FilePathE + 42
6   Chromium Embedded Framework         0x0000000121148cf8 _ZN12_GLOBAL__N_127OverrideFrameworkBundlePathEv + 40
7   Chromium Embedded Framework         0x00000001211467aa _ZN15CefMainDelegate20BasicStartupCompleteEPi + 58
8   Chromium Embedded Framework         0x000000012c076e6a _ZN7content21ContentMainRunnerImpl10InitializeERKNS_17ContentMainParamsE + 506
9   Chromium Embedded Framework         0x0000000120f55c46 _ZN10CefContext10InitializeERK11CefMainArgsRK13CefStructBaseI17CefSettingsTraitsE9CefRefPtrI6CefAppEPv + 646
10  Chromium Embedded Framework         0x0000000120f5591b _Z13CefInitializeRK11CefMainArgsRK13CefStructBaseI17CefSettingsTraitsE9CefRefPtrI6CefAppEPv + 411
11  Chromium Embedded Framework         0x0000000120d961c4 cef_initialize + 628
12  libchromium_loader.dylib            0x00000001209b0224 _Z13CefInitializeRK11CefMainArgsRK13CefStructBaseI17CefSettingsTraitsE9CefRefPtrI6CefAppEPv + 420
13  libchromium_loader.dylib            0x00000001209645f1 Java_org_embedded_browser_Chromium_browser_1init + 897
14  ???                                 0x0000000102bab9d4 0x0 + 4340758996
15  ???                                 0x0000000102b9c2bd 0x0 + 4340695741

./tools/run.sh: line 52: 43727 Trace/BPT trap: 5       "$JAVA_HOME$JAVA_BIN" -XstartOnFirstThread -cp "$PROJECT_DIR/java/lib/mac/swt64.jar:$BUILD_DIR/$JAR_NAME" -Djava.library.path="$BUILD_DIR:$DYLD_LIBRARY_PATH" -Duser.dir="$PROJECT_DIR/java" org.embedded.browser.SampleBrowserSWT

Can somebody throw some light of what's going wrong. Please help.

**Comment by wjywbs** [comment]
Version 2623 is not supported yet. Could you try the 3.2526 branch and download version 2526 of cefclient.app?
